const initialQuotes = [
  // 1-50 are already inserted by the user, but we'll include them and many more
  // to ensure a robust library of 150+ quotes and secrets.
  { QuoteText: "The only way to do great work is to love what you do.", Author: "Steve Jobs", IsSecret: 0 },
  { QuoteText: "Be yourself; everyone else is already taken.", Author: "Oscar Wilde", IsSecret: 0 },
  { QuoteText: "Remember: Take a deep breath. You are doing much better than you think you are.", Author: "Myself", IsSecret: 1 },
  { QuoteText: "Act as if what you do makes a difference. It does.", Author: "William James", IsSecret: 0 },
  { QuoteText: "Success is not final, failure is not fatal: it is the courage to continue that counts.", Author: "Winston Churchill", IsSecret: 0 },
  { QuoteText: "Never bend your head. Always hold it high. Look the world straight in the eye.", Author: "Helen Keller", IsSecret: 0 },
  { QuoteText: "What you get by achieving your goals is not as important as what you become by achieving your goals.", Author: "Zig Ziglar", IsSecret: 0 },
  { QuoteText: "Believe you can and you're halfway there.", Author: "Theodore Roosevelt", IsSecret: 0 },
  { QuoteText: "When you have a dream, you've got to grab it and never let go.", Author: "Carol Burnett", IsSecret: 0 },
  { QuoteText: "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", Author: "Jimmy Dean", IsSecret: 0 },
  { QuoteText: "No matter what what people tell you, words and ideas can change the world.", Author: "Robin Williams", IsSecret: 0 },
  { QuoteText: "It is during our darkest moments that we must focus to see the light.", Author: "Aristotle", IsSecret: 0 },
  { QuoteText: "Keep your face always toward the sunshine, and shadows will fall behind you.", Author: "Walt Whitman", IsSecret: 0 },
  { QuoteText: "You are never too old to set another goal or to dream a new dream.", Author: "C.S. Lewis", IsSecret: 0 },
  { QuoteText: "The bad news is time flies. The good news is you're the pilot.", Author: "Michael Altshuler", IsSecret: 0 },
  { QuoteText: "Do not allow people to dim your shine because they are blinded by your light.", Author: "Lady Gaga", IsSecret: 0 },
  { QuoteText: "You make a life out of what you have, not what you're missing.", Author: "Kate Morton", IsSecret: 0 },
  { QuoteText: "The secret of getting ahead is getting started.", Author: "Mark Twain", IsSecret: 0 },
  { QuoteText: "The best way to predict the future is to create it.", Author: "Peter Drucker", IsSecret: 0 },
  { QuoteText: "It always seems impossible until it's done.", Author: "Nelson Mandela", IsSecret: 0 },
  { QuoteText: "Happiness is not something ready-made. It comes from your own actions.", Author: "Dalai Lama", IsSecret: 0 },
  { QuoteText: "Don't count the days, make the days count.", Author: "Muhammad Ali", IsSecret: 0 },
  { QuoteText: "We become what we think about.", Author: "Earl Nightingale", IsSecret: 0 },
  { QuoteText: "An unexamined life is not worth living.", Author: "Socrates", IsSecret: 0 },
  { QuoteText: "The only true wisdom is in knowing you know nothing.", Author: "Socrates", IsSecret: 0 },
  { QuoteText: "Everything you've ever wanted is on the other side of fear.", Author: "George Addair", IsSecret: 0 },
  { QuoteText: "Opportunities don't happen. You create them.", Author: "Chris Grosser", IsSecret: 0 },
  { QuoteText: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", Author: "Eleanor Roosevelt", IsSecret: 0 },
  { QuoteText: "A person who never made a mistake never tried anything new.", Author: "Albert Einstein", IsSecret: 0 },
  { QuoteText: "Your time is limited, so don't waste it living someone else's life.", Author: "Steve Jobs", IsSecret: 0 },
  { QuoteText: "The only impossible journey is the one you never begin.", Author: "Tony Robbins", IsSecret: 0 },
  { QuoteText: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", Author: "Helen Keller", IsSecret: 0 },
  { QuoteText: "In the middle of every difficulty lies opportunity.", Author: "Albert Einstein", IsSecret: 0 },
  { QuoteText: "Go confidently in the direction of your dreams. Live the life you have imagined.", Author: "Henry David Thoreau", IsSecret: 0 },
  { QuoteText: "Do what you can, with what you have, where you are.", Author: "Theodore Roosevelt", IsSecret: 0 },
  { QuoteText: "If you want to lift yourself up, lift up someone else.", Author: "Booker T. Washington", IsSecret: 0 },
  { QuoteText: "You miss 100% of the shots you don't take.", Author: "Wayne Gretzky", IsSecret: 0 },
  { QuoteText: "Whether you think you can or you think you can't, you're right.", Author: "Henry Ford", IsSecret: 0 },
  { QuoteText: "Perfection is not attainable, but if we chase perfection we can catch excellence.", Author: "Vince Lombardi", IsSecret: 0 },
  { QuoteText: "I have not failed. I've just found 10,000 ways that won't work.", Author: "Thomas A. Edison", IsSecret: 0 },
  { QuoteText: "Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus.", Author: "Alexander Graham Bell", IsSecret: 0 },
  { QuoteText: "There is only one corner of the universe you can be certain of improving, and that's your own self.", Author: "Aldous Huxley", IsSecret: 0 },
  { QuoteText: "Waste no more time arguing about what a good man should be. Be one.", Author: "Marcus Aurelius", IsSecret: 0 },
  { QuoteText: "The happiness of your life depends upon the quality of your thoughts.", Author: "Marcus Aurelius", IsSecret: 0 },
  { QuoteText: "You have power over your mind - not outside events. Realize this, and you will find strength.", Author: "Marcus Aurelius", IsSecret: 0 },
  { QuoteText: "We suffer more often in imagination than in reality.", Author: "Seneca", IsSecret: 0 },
  { QuoteText: "If a man knows not which port he sails, no wind is favorable.", Author: "Seneca", IsSecret: 0 },
  { QuoteText: "Begin at once to live, and count each separate day as a separate life.", Author: "Seneca", IsSecret: 0 },
  { QuoteText: "He who is brave is free.", Author: "Seneca", IsSecret: 0 },
  { QuoteText: "The point is not to pay back kindness, but to pass it on.", Author: "Julia Alvarez", IsSecret: 0 },
  { QuoteText: "Make each day your masterpiece.", Author: "John Wooden", IsSecret: 0 },

  // Additional 100+ Inspirational Quotes & Secrets (to exceed 150 total quotes)
  { QuoteText: "Secret: Your value is not defined by your productivity. Rest is productive too.", Author: "Self-Compassion", IsSecret: 1 },
  { QuoteText: "Secret: It is okay to be a beginner. Every master started with a clumsy first step.", Author: "Encouragement", IsSecret: 1 },
  { QuoteText: "Secret: Be gentle with yourself. You are growing at your own perfect pace.", Author: "Self-Care", IsSecret: 1 },
  { QuoteText: "Secret: Stop comparing your behind-the-scenes with everyone else's highlight reel.", Author: "Reality Check", IsSecret: 1 },
  { QuoteText: "Secret: You have overcome 100% of your hardest days so far. You are incredibly resilient.", Author: "Inner Strength", IsSecret: 1 },
  { QuoteText: "Secret: You do not need anyone's permission to live a life that makes you happy.", Author: "Freedom", IsSecret: 1 },
  { QuoteText: "Secret: Saying 'no' to others is often saying 'yes' to your own mental well-being.", Author: "Boundaries", IsSecret: 1 },
  { QuoteText: "Secret: Small progress is still progress. Celebrate every tiny win today.", Author: "Daily Reminder", IsSecret: 1 },
  { QuoteText: "Secret: The version of you that you are building is worth letting go of old habits.", Author: "Transformation", IsSecret: 1 },
  { QuoteText: "Secret: Trust the timing of your life. What is meant for you will not bypass you.", Author: "Trust", IsSecret: 1 },

  { QuoteText: "The journey of a thousand miles begins with one step.", Author: "Lao Tzu", IsSecret: 0 },
  { QuoteText: "That which does not kill us makes us stronger.", Author: "Friedrich Nietzsche", IsSecret: 0 },
  { QuoteText: "Dream big and dare to fail.", QuoteText: "Dream big and dare to fail.", Author: "Norman Vaughan", IsSecret: 0 },
  { QuoteText: "It is not length of life, but depth of life.", Author: "Ralph Waldo Emerson", IsSecret: 0 },
  { QuoteText: "The only limit to our realization of tomorrow will be our doubts of today.", Author: "Franklin D. Roosevelt", IsSecret: 0 },
  { QuoteText: "Do one thing every day that scares you.", Author: "Eleanor Roosevelt", IsSecret: 0 },
  { QuoteText: "If you change the way you look at things, the things you look at change.", Author: "Wayne Dyer", IsSecret: 0 },
  { QuoteText: "It is never too late to be what you might have been.", Author: "George Eliot", IsSecret: 0 },
  { QuoteText: "Strive not to be a success, but rather to be of value.", Author: "Albert Einstein", IsSecret: 0 },
  { QuoteText: "You must be the change you wish to see in the world.", Author: "Mahatma Gandhi", IsSecret: 0 },
  { QuoteText: "I have learned over the years that when one's mind is made up, this diminishes fear.", Author: "Rosa Parks", IsSecret: 0 },
  { QuoteText: "I would rather die of passion than of boredom.", Author: "Vincent van Gogh", IsSecret: 0 },
  { QuoteText: "A warm smile is the universal language of kindness.", Author: "William Arthur Ward", IsSecret: 0 },
  { QuoteText: "The most difficult thing is the decision to act, the rest is merely tenacity.", Author: "Amelia Earhart", IsSecret: 0 },
  { QuoteText: "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", Author: "Plato", IsSecret: 0 },
  { QuoteText: "Nothing is impossible, the word itself says 'I'm possible!'", Author: "Audrey Hepburn", IsSecret: 0 },
  { QuoteText: "Life is what happens when you're busy making other plans.", Author: "John Lennon", IsSecret: 0 },
  { QuoteText: "The essence of the beautiful arts is gratitude.", Author: "Friedrich Nietzsche", IsSecret: 0 },
  { QuoteText: "The power of imagination makes us infinite.", Author: "John Muir", IsSecret: 0 },
  { QuoteText: "Quality is not an act, it is a habit.", Author: "Aristotle", IsSecret: 0 },
  { QuoteText: "Simplicity is the ultimate sophistication.", Author: "Leonardo da Vinci", IsSecret: 0 },
  { QuoteText: "Light tomorrow with today!", Author: "Elizabeth Barrett Browning", IsSecret: 0 },
  { QuoteText: "What we think, we become.", Author: "Buddha", IsSecret: 0 },
  { QuoteText: "Fall seven times and stand up eight.", Author: "Japanese Proverb", IsSecret: 0 },
  { QuoteText: "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", Author: "Bill Keane", IsSecret: 0 },
  { QuoteText: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", Author: "Ralph Waldo Emerson", IsSecret: 0 },
  { QuoteText: "Don't walk behind me; I may not lead. Don't walk in front of me; I may not follow. Just walk beside me and be my friend.", Author: "Albert Camus", IsSecret: 0 },
  { QuoteText: "Integrity is doing the right thing even when no one is watching.", Author: "C.S. Lewis", IsSecret: 0 },
  { QuoteText: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", Author: "Aristotle", IsSecret: 0 },
  { QuoteText: "If you cannot do great things, do small things in a great way.", Author: "Napoleon Hill", IsSecret: 0 },
  { QuoteText: "Live as if you were to die tomorrow. Learn as if you were to live forever.", Author: "Mahatma Gandhi", IsSecret: 0 },
  { QuoteText: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", Author: "Mark Twain", IsSecret: 0 },
  { QuoteText: "The future belongs to those who believe in the beauty of their dreams.", Author: "Eleanor Roosevelt", IsSecret: 0 },
  { QuoteText: "Well done is better than well said.", Author: "Benjamin Franklin", IsSecret: 0 },
  { QuoteText: "It is during our darkest moments that we must focus to see the light.", Author: "Aristotle", IsSecret: 0 },
  { QuoteText: "Quiet minds cannot be perplexed or frightened but go on in fortune or misfortune at their own private pace.", Author: "Robert Louis Stevenson", IsSecret: 0 },
  { QuoteText: "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.'", Author: "Mary Anne Radmacher", IsSecret: 0 },
  { QuoteText: "You are never too old to set another goal or to dream a new dream.", Author: "Les Brown", IsSecret: 0 },
  { QuoteText: "Be not afraid of greatness. Some are born great, some achieve greatness, and some have greatness thrust upon 'em.", Author: "William Shakespeare", IsSecret: 0 },
  { QuoteText: "The only limit to our realization of tomorrow will be our doubts of today.", Author: "Franklin D. Roosevelt", IsSecret: 0 },
  { QuoteText: "Out of difficulties grow miracles.", Author: "Jean de la Bruyere", IsSecret: 0 },
  { QuoteText: "If you want to be happy, be.", Author: "Leo Tolstoy", IsSecret: 0 },
  { QuoteText: "Wisdom begins in wonder.", Author: "Socrates", IsSecret: 0 },
  { QuoteText: "You do not find a happy life. You make it.", Author: "Camilla Eyring Kimball", IsSecret: 0 },
  { QuoteText: "Choose a job you love, and you will never have to work a day in your life.", Author: "Confucius", IsSecret: 0 },
  { QuoteText: "Action is the foundational key to all success.", Author: "Pablo Picasso", IsSecret: 0 },
  { QuoteText: "We must embrace pain and burn it as fuel for our journey.", Author: "Kenji Miyazawa", IsSecret: 0 },
  { QuoteText: "The best preparation for tomorrow is doing your best today.", Author: "H. Jackson Brown, Jr.", IsSecret: 0 },
  { QuoteText: "Failure is the condiment that gives success its flavor.", Author: "Truman Capote", IsSecret: 0 },
  { QuoteText: "The mind is everything. What you think you become.", Author: "Buddha", IsSecret: 0 },
  { QuoteText: "Start where you are. Use what you have. Do what you can.", Author: "Arthur Ashe", IsSecret: 0 },
  { QuoteText: "Change your thoughts and you change your world.", Author: "Norman Vincent Peale", IsSecret: 0 },
  { QuoteText: "A goal is a dream with a deadline.", Author: "Napoleon Hill", IsSecret: 0 },
  { QuoteText: "The root of education is bitter, but the fruit is sweet.", Author: "Aristotle", IsSecret: 0 },
  { QuoteText: "All our dreams can come true, if we have the courage to pursue them.", Author: "Walt Disney", IsSecret: 0 },
  { QuoteText: "The starting point of all achievement is desire.", Author: "Napoleon Hill", IsSecret: 0 },
  { QuoteText: "In order to succeed, we must first believe that we can.", Author: "Nikos Kazantzakis", IsSecret: 0 },
  { QuoteText: "The best way out is always through.", Author: "Robert Frost", IsSecret: 0 },
  { QuoteText: "There is nothing permanent except change.", Author: "Heraclitus", IsSecret: 0 },
  { QuoteText: "Our life is frittered away by detail. Simplify, simplify.", Author: "Henry David Thoreau", IsSecret: 0 },
  { QuoteText: "You are today where your thoughts have brought you; you will be tomorrow where your thoughts take you.", Author: "James Allen", IsSecret: 0 },
  { QuoteText: "He who has a why to live can bear almost any how.", Author: "Friedrich Nietzsche", IsSecret: 0 },
  { QuoteText: "Keep face to sunshine, and shadows will fall behind you.", Author: "Walt Whitman", IsSecret: 0 },
  { QuoteText: "You must do the things you think you cannot do.", Author: "Eleanor Roosevelt", IsSecret: 0 },
  { QuoteText: "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.", Author: "Helen Keller", IsSecret: 0 },
  { QuoteText: "Happiness is not by chance, but by choice.", Author: "Jim Rohn", IsSecret: 0 },
  { QuoteText: "If you correct your mind, the rest of your life will fall into place.", Author: "Lao Tzu", IsSecret: 0 },
  { QuoteText: "Live life to the fullest, and focus on the positive.", Author: "Matt Cameron", IsSecret: 0 },
  { QuoteText: "What we achieve inwardly will change outer reality.", Author: "Plutarch", IsSecret: 0 },
  { QuoteText: "It is the side-effects of a life lived for others that are the most beautiful.", Author: "Albert Schweitzer", IsSecret: 0 },
  { QuoteText: "The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.", Author: "Bob Marley", IsSecret: 0 },
  { QuoteText: "A room without books is like a body without a soul.", Author: "Marcus Tullius Cicero", IsSecret: 0 },
  { QuoteText: "The only wisdom is in knowing you know nothing.", Author: "Socrates", IsSecret: 0 },
  { QuoteText: "The standard you walk past is the standard you accept.", Author: "David Morrison", IsSecret: 0 },
  { QuoteText: "Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart.", Author: "Marcus Aurelius", IsSecret: 0 },
  { QuoteText: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", Author: "Marcus Aurelius", IsSecret: 0 },
  { QuoteText: "When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love.", Author: "Marcus Aurelius", IsSecret: 0 },
  { QuoteText: "Loss is nothing else but change, and change is Nature's delight.", Author: "Marcus Aurelius", IsSecret: 0 },
  { QuoteText: "If it is not right, do not do it; if it is not true, do not say it.", Author: "Marcus Aurelius", IsSecret: 0 },
  { QuoteText: "Dwell on the beauty of life. Watch the stars, and run with them.", Author: "Marcus Aurelius", IsSecret: 0 },
  { QuoteText: "The best revenge is to be unlike him who performed the injury.", Author: "Marcus Aurelius", IsSecret: 0 },
  { QuoteText: "It is not death that a man should fear, but he should fear never beginning to live.", Author: "Marcus Aurelius", IsSecret: 0 },
  { QuoteText: "How much time he gains who does not look to see what his neighbour says or does or thinks, but only at what he does himself, to make it just and holy.", Author: "Marcus Aurelius", IsSecret: 0 },
  { QuoteText: "Accept whatever comes to you woven in the pattern of your destiny, for what could more aptly fit your needs?", Author: "Marcus Aurelius", IsSecret: 0 },
  { QuoteText: "Waste no more time arguing about what a good man should be. Be one.", Author: "Marcus Aurelius", IsSecret: 0 },
  { QuoteText: "No man is free who is not master of himself.", Author: "Epictetus", IsSecret: 0 },
  { QuoteText: "First say to yourself what you would be; and then do what you have to do.", Author: "Epictetus", IsSecret: 0 },
  { QuoteText: "If you want to improve, be content to be thought foolish and stupid.", Author: "Epictetus", IsSecret: 0 },
  { QuoteText: "Control your passions lest they take vengeance on you.", Author: "Epictetus", IsSecret: 0 },
  { QuoteText: "The key is to keep company only with people who uplift you, whose presence calls forth your best.", Author: "Epictetus", IsSecret: 0 },
  { QuoteText: "People are not disturbed by things, but by the view they take of them.", Author: "Epictetus", IsSecret: 0 },
  { QuoteText: "Make the best use of what is in your power, and take the rest as it happens.", Author: "Epictetus", IsSecret: 0 },
  { QuoteText: "Wealth consists not in having great possessions, but in having few wants.", Author: "Epictetus", IsSecret: 0 },
  { QuoteText: "Only the educated are free.", Author: "Epictetus", IsSecret: 0 },
  { QuoteText: "A ship should not ride on a single anchor, nor life on a single hope.", Author: "Epictetus", IsSecret: 0 },
  { QuoteText: "Associate with people who are likely to improve you.", Author: "Seneca", IsSecret: 0 },
  { QuoteText: "If you really want to escape the things that harass you, what you're needing is not to be in a different place but to be a different person.", Author: "Seneca", IsSecret: 0 },
  { QuoteText: "We suffer more often in imagination than in reality.", Author: "Seneca", IsSecret: 0 },
  { QuoteText: "While we waste our time hesitating and postponing, life goes on.", Author: "Seneca", IsSecret: 0 },
  { QuoteText: "It is not that we have a short time to live, but that we waste a lot of it.", Author: "Seneca", IsSecret: 0 },
  { QuoteText: "True happiness is to enjoy the present, without anxious dependence upon the future.", Author: "Seneca", IsSecret: 0 },
  { QuoteText: "As long as you live, keep learning how to live.", Author: "Seneca", IsSecret: 0 },
  { QuoteText: "He who is brave is free.", Author: "Seneca", IsSecret: 0 },
  { QuoteText: "Luck is what happens when preparation meets opportunity.", Author: "Seneca", IsSecret: 0 },
  { QuoteText: "Difficulties strengthen the mind, as labor does the body.", Author: "Seneca", IsSecret: 0 }
];

const initialChecklist = [
  "☀️ Wake up before 4am",
  "💧 Take shower",
  "🧘 Meditate for 10 minutes",
  "💧 Drink 8 glasses of water",
  "📖 Read 10 pages of a book",
  "🏃 Gym/Badminton",
  "🍏 Eat all three meals",
  "✍️ Journal 10 minutes",
  "📖 Study for 1 hour straight",
  "📖 DSA - 3 problems",
  "💻 Do a project and post it to LinkedIn and GitHub",
  "🧹 Organize your room",
  "📵 Digital detox (No screens for more than 2 hours)",
  "😴 Get 6 hours of quality sleep"
];

module.exports = { initialQuotes, initialChecklist };
